import '../styles/globals.scss'
import { headers } from 'next/headers'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children, mobile, desktop }) {
    const headersList = await headers()
    const userAgent = headersList.get('user-agent')
    const isMobile = /mobi|Android/i.test(userAgent.toLowerCase())
    return (
        <html lang="en">
            <body>
                <h1>公共 layout</h1>
                <div>{isMobile ? mobile : desktop}</div>
            </body>
        </html>
    )
}
